# Generated by Django 5.1.1 on 2024-09-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='atividades',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='comunicacao',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='entregas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='equipe',
            field=models.IntegerField(default=0),
        ),
    ]
